name: Alex Recommends

on: pull_request

jobs:
  alex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Comment on new PR
      uses: brown-ccv/alex-recommends@v1.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message_id: 'alex'
        no_binary: false
        profanity_sureness: 2
        pr_only: false
        glob_pattern: "services/**"
